# Chương 1 - Khám phá dữ liệu
## 1.1 Thống kê mô tả
### 1.1.1 Import thư viện
### 1.1.2 Đọc dữ liệu
### 1.1.3 Tính toán các thước đo
### 1.1.4 Nhận xét

### 1.1.1 Import thư viện

In [1]:
#Import libaries
try:
    import pandas as pd
    print("Pandas downloaded successfully ",pd.__version__)
except ImportError:
    print("Pandas download failed")

try:
    import numpy as np
    print("Numpy download successfull ",np.__version__)
except ImportError:
    print("Numpy downloaded failed")

try:
    import matplotlib.pyplot as plt
    print("Matplotlib download successfully ")
except ImportError:
    print("Matplotlib download failed")

try:
    import seaborn as sns
    print("Seaborn download successfully")
except ImportError:
    print("Seaborn download failed")
    
print("All libaries downloaded successfully")

Pandas downloaded successfully  3.0.5
Numpy download successfull  2.5.3
Matplotlib download successfully
Seaborn download successfully
All libaries downloaded successfully

In [2]:
%matplotlib tk
#Show diagrams in new window

In [3]:
# Get data
try:
    cusData = pd.read_csv('/Users/phatpeso/Desktop/Phat/Python/Data Mining/data/raw/customer_segmentation_data.csv')
    #reset index
    cusData.index = range(1,len(cusData)+1)
    display(cusData.head(10))
except NameError:
    print("Import data failed")

,Customer ID,Age,Gender,Marital Status,Education Level,Geographic Information,Occupation,Income Level,Behavioral Data,Purchase History,Interactions with Customer Service,Insurance Products Owned,Coverage Amount,Premium Amount,Policy Type,Customer Preferences,Preferred Communication Channel,Preferred Contact Time,Preferred Language,Segmentation Group
1,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,policy5,04-10-2018,Phone,policy2,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5
2,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,policy5,11-06-2018,Chat,policy1,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5
3,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,policy5,06-05-2021,Email,policy3,773926,4413,Group,Email,Mail,Evening,German,Segment3
4,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,policy5,09-02-2018,Chat,policy2,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3
5,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,policy1,09-10-2018,Chat,policy4,366506,1276,Family,Email,Text,Weekends,English,Segment2
6,60937,41,Female,Separated,Master's Degree,Uttar Pradesh,Nurse,87188,policy5,9/19/2020,Chat,policy1,570757,1106,Individual,Text,Text,Afternoon,English,Segment4
7,37676,55,Male,Single,Bachelor's Degree,Rajasthan,Manager,94891,policy3,07-04-2021,Chat,policy2,604069,3661,Group,In-Person Meeting,Text,Weekends,Mandarin,Segment5
8,54100,35,Male,Married,Master's Degree,Himachal Pradesh,Artist,61003,policy1,11-01-2021,Phone,policy3,418997,1148,Business,Email,Phone,Morning,English,Segment5
9,30476,43,Female,Single,Doctorate,Manipur,Salesperson,116249,policy1,9/20/2020,Mobile App,policy4,319423,2612,Business,In-Person Meeting,Text,Weekends,Mandarin,Segment2
10,39071,32,Female,Single,Master's Degree,Gujarat,Artist,49083,policy3,4/24/2020,Phone,policy1,701577,4595,Group,Phone,Email,Weekends,English,Segment2

### 1.1.2 Đọc dữ liệu

In [4]:
cusData.describe()

,Customer ID,Age,Income Level,Coverage Amount,Premium Amount
count,53503.000000,53503.000000,53503.000000,53503.000000,53503.000000
mean,52265.204998,44.140945,82768.324318,492580.789638,3023.702447
std,28165.000067,15.079486,36651.075670,268405.505571,1285.834295
min,1.000000,18.000000,20001.000000,50001.000000,500.000000
25%,28950.500000,32.000000,51568.500000,249613.500000,1817.000000
50%,55858.000000,43.000000,80719.000000,477261.000000,3194.000000
75%,76096.000000,57.000000,115973.500000,739124.000000,4311.500000
max,100000.000000,70.000000,149999.000000,1000000.000000,5000.000000

In [5]:
#Review data
print("Your data has",cusData.shape,"rows and cols")
print("There are cols in your data: ",cusData.columns)
print("The type of cols:",cusData.dtypes)
print("Review data: ",cusData.info())
print("Describe data: ", cusData.describe())
print("Describe object data",cusData.describe(include='object'))

Your data has (53503, 20) rows and cols
There are cols in your data:  Index(['Customer ID', 'Age', 'Gender', 'Marital Status', 'Education Level',
       'Geographic Information', 'Occupation', 'Income Level',
       'Behavioral Data', 'Purchase History',
       'Interactions with Customer Service', 'Insurance Products Owned',
       'Coverage Amount', 'Premium Amount', 'Policy Type',
       'Customer Preferences', 'Preferred Communication Channel',
       'Preferred Contact Time', 'Preferred Language', 'Segmentation Group'],
      dtype='str')
The type of cols: Customer ID                           int64
Age                                   int64
Gender                                  str
Marital Status                          str
Education Level                         str
Geographic Information                  str
Occupation                              str
Income Level                          int64
Behavioral Data                         str
Purchase History                        str
Interactions with Customer Service      str
Insurance Products Owned                str
Coverage Amount                       int64
Premium Amount                        int64
Policy Type                             str
Customer Preferences                    str
Preferred Communication Channel         str
Preferred Contact Time                  str
Preferred Language                      str
Segmentation Group                      str
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 53503 entries, 1 to 53503
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Customer ID                         53503 non-null  int64
 1   Age                                 53503 non-null  int64
 2   Gender                              53503 non-null  str
 3   Marital Status                      53503 non-null  str
 4   Education Level                     53503 non-null  str
 5   Geographic Information              53503 non-null  str
 6   Occupation                          53503 non-null  str
 7   Income Level                        53503 non-null  int64
 8   Behavioral Data                     53503 non-null  str
 9   Purchase History                    53503 non-null  str
 10  Interactions with Customer Service  53503 non-null  str
 11  Insurance Products Owned            53503 non-null  str
 12  Coverage Amount                     53503 non-null  int64
 13  Premium Amount                      53503 non-null  int64
 14  Policy Type                         53503 non-null  str
 15  Customer Preferences                53503 non-null  str
 16  Preferred Communication Channel     53503 non-null  str
 17  Preferred Contact Time              53503 non-null  str
 18  Preferred Language                  53503 non-null  str
 19  Segmentation Group                  53503 non-null  str
dtypes: int64(5), str(15)
memory usage: 8.2 MB
Review data:  None
Describe data:           Customer ID           Age   Income Level  Coverage Amount  \
count   53503.000000  53503.000000   53503.000000     53503.000000
mean    52265.204998     44.140945   82768.324318    492580.789638
std     28165.000067     15.079486   36651.075670    268405.505571
min         1.000000     18.000000   20001.000000     50001.000000
25%     28950.500000     32.000000   51568.500000    249613.500000
50%     55858.000000     43.000000   80719.000000    477261.000000
75%     76096.000000     57.000000  115973.500000    739124.000000
max    100000.000000     70.000000  149999.000000   1000000.000000

       Premium Amount
count    53503.000000
mean      3023.702447
std       1285.834295
min        500.000000
25%       1817.000000
50%       3194.000000
75%       4311.500000
max       5000.000000
Describe object data        Gender Marital Status   Education Level Geographic Information  \
count   53503          53503             53503                  53503
unique      2              5                 5                     35
top      Male        Married  Associate Degree            Lakshadweep
freq    27499          13219             12213                   2140

         Occupation Behavioral Data Purchase History  \
count         53503           53503            53503
unique            9               5             2016
top     Salesperson         policy3       03-12-2018
freq           7919           15761              173

       Interactions with Customer Service Insurance Products Owned  \
count                               53503                    53503
unique                                  5                        5
top                                  Chat                  policy1
freq                                14153                    13365

       Policy Type Customer Preferences Preferred Communication Channel  \
count        53503                53503                           53503
unique           4                    5                               5
top          Group                 Mail               In-Person Meeting
freq         18255                11887                           14311

       Preferred Contact Time Preferred Language Segmentation Group
count                   53503              53503              53503
unique                      5                  5                  5
top                  Weekends             German           Segment5
freq                    14092              14452              13976

/var/folders/1n/h0qqn2cj7wlg049lg26yxqjw0000gn/T/ipykernel_17511/3513511897.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print("Describe object data",cusData.describe(include='object'))

In [6]:

#Cleaning data
print("Total null in data: ", cusData.isnull().sum())
print("Proportion null: ",cusData.isnull().sum()/len(cusData)*100)

Total null in data:  Customer ID                           0
Age                                   0
Gender                                0
Marital Status                        0
Education Level                       0
Geographic Information                0
Occupation                            0
Income Level                          0
Behavioral Data                       0
Purchase History                      0
Interactions with Customer Service    0
Insurance Products Owned              0
Coverage Amount                       0
Premium Amount                        0
Policy Type                           0
Customer Preferences                  0
Preferred Communication Channel       0
Preferred Contact Time                0
Preferred Language                    0
Segmentation Group                    0
dtype: int64
Proportion null:  Customer ID                           0.0
Age                                   0.0
Gender                                0.0
Marital Status                        0.0
Education Level                       0.0
Geographic Information                0.0
Occupation                            0.0
Income Level                          0.0
Behavioral Data                       0.0
Purchase History                      0.0
Interactions with Customer Service    0.0
Insurance Products Owned              0.0
Coverage Amount                       0.0
Premium Amount                        0.0
Policy Type                           0.0
Customer Preferences                  0.0
Preferred Communication Channel       0.0
Preferred Contact Time                0.0
Preferred Language                    0.0
Segmentation Group                    0.0
dtype: float64

### 1.1.3 Tính toán các thước đo

In [7]:
# handle with null
cusData_originall = cusData.copy()
#Fill nan with median of col
cusData['Income Level'] = cusData['Income Level'].fillna(cusData['Income Level'].median())
#Drop nan in Age col
cusData = cusData.dropna(subset=['Age'])

In [8]:
#Change type of Purchase History col
cusData['Purchase History'] = pd.to_datetime(cusData['Purchase History'], format='mixed',errors='coerce')
cusData['Purchase History'].head(5)

#Create a new col 
cusData['Premium Ratio'] = cusData['Premium Amount']/cusData['Coverage Amount']
cusData.head(10)

,Customer ID,Age,Gender,Marital Status,Education Level,Geographic Information,Occupation,Income Level,Behavioral Data,Purchase History,...,Insurance Products Owned,Coverage Amount,Premium Amount,Policy Type,Customer Preferences,Preferred Communication Channel,Preferred Contact Time,Preferred Language,Segmentation Group,Premium Ratio
1,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,policy5,2018-04-10,...,policy2,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5,0.007499
2,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,policy5,2018-11-06,...,policy1,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5,0.002520
3,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,policy5,2021-06-05,...,policy3,773926,4413,Group,Email,Mail,Evening,German,Segment3,0.005702
4,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,policy5,2018-09-02,...,policy2,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3,0.005511
5,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,policy1,2018-09-10,...,policy4,366506,1276,Family,Email,Text,Weekends,English,Segment2,0.003482
6,60937,41,Female,Separated,Master's Degree,Uttar Pradesh,Nurse,87188,policy5,2020-09-19,...,policy1,570757,1106,Individual,Text,Text,Afternoon,English,Segment4,0.001938
7,37676,55,Male,Single,Bachelor's Degree,Rajasthan,Manager,94891,policy3,2021-07-04,...,policy2,604069,3661,Group,In-Person Meeting,Text,Weekends,Mandarin,Segment5,0.006061
8,54100,35,Male,Married,Master's Degree,Himachal Pradesh,Artist,61003,policy1,2021-11-01,...,policy3,418997,1148,Business,Email,Phone,Morning,English,Segment5,0.002740
9,30476,43,Female,Single,Doctorate,Manipur,Salesperson,116249,policy1,2020-09-20,...,policy4,319423,2612,Business,In-Person Meeting,Text,Weekends,Mandarin,Segment2,0.008177
10,39071,32,Female,Single,Master's Degree,Gujarat,Artist,49083,policy3,2020-04-24,...,policy1,701577,4595,Group,Phone,Email,Weekends,English,Segment2,0.006550

# 3. Phân tích đơn biến (Univariate)
## 3.1. Biến số (Age, Income Level, Coverage Amount, Premium Amount)

In [9]:
print("Describe Age colunm")
cusData['Age'].describe()

Describe Age colunm

count    53503.000000
mean        44.140945
std         15.079486
min         18.000000
25%         32.000000
50%         43.000000
75%         57.000000
max         70.000000
Name: Age, dtype: float64

In [10]:
#Histogram
plt.Figure(figsize=(10,5))
sns.histplot(data=cusData, x='Age', bins= 20, kde=True)
plt.title('Phân phối độ tuổi')
plt.show()

In [11]:
#Boxplot (show Outler)
plt.figure(figsize=(10,5))
sns.boxplot(data=cusData,x='Income Level')
plt.title('Income Level')
plt.show()

In [12]:
#Vionlin plot
plt.figure(figsize=(10,5))
sns.violinplot(data=cusData, x='Premium Amount')
plt.title('Premium Amount')
plt.show()

## 3.2. Biến phân loại (Gender, Marital Status, Education Level, ...)

In [13]:
# Frequency counting
cusData['Gender'].value_counts()

Gender
Male      27499
Female    26004
Name: count, dtype: int64

In [14]:
#Bar chart
plt.figure(figsize=(10,5))
sns.countplot(data=cusData, x='Gender')
plt.title('So luong khac hang theo gioi tinh')
plt.show()

In [ ]:
#Pie chart
cusData['Segmentation Group'].value_counts().plot(
    kind='pie', autopct = '%1.1f%%',figsize=(8,8)
)
plt.title('Ty le cac nhom phan khuc')
plt.ylabel('')
plt.show()

: